version: '3.9'
services:
  # api:
  #   container_name: api
  #   build: ./
  #   command: npm run start
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   depends_on:
  #     - db_pg
  #   networks:
  #     - pomodoro_backend_net

  db_pg:
    container_name: road_inspector_pg
    image: postgres:15.1-alpine
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - pip_network
networks:
  pip_network:
